version: '2'
services:
  keycloak:
    image: jboss/keycloak:12.0.4
    container_name: keycloak
    ports:
      - "8080:8080"
    volumes:
      - ./realm-config:/tmp/jboss/keycloak/realm-config
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/jboss/keycloak/realm-config/realm-export.json
      DB_VENDOR: h2
